### ISSUE TITLE
Firefox doesn't like event.toElement

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paellaengage#1]
Firefox (23.0.1) doesn't recognize "event.toElement" from social.js (paella_plugins.js) on embed content click event. It logs an event.toElement is undefined message.

Event target compatibility: http://www.quirksmode.org/dom/w3c_events.html#targets

Problem line from social.js:
var value = event.toElement.value;

**Comment by kiranmoy1994** [comment]
Firefox does not support event.toElement. 
Should use **event.target**

**Comment by karendolan** [comment]
Wow, from 2013! So same issue in FF v74
 https://github.com/polimediaupv/paellaengage/search?q=event.toElement.value&unscoped_q=event.toElement.value

per https://www.quirksmode.org/js/events_mouse.html
```
function doSomething(e) {
	if (!e) var e = window.event;
	var relTarg = e.relatedTarget || e.toElement;
}
```

**Comment by turro** [comment]
Anyway this repository is completely obsolete (it's for MH 1.4). I wonder if it would make sense to close it

**Comment by karendolan** [comment]
> Anyway this repository is completely obsolete (it's for MH 1.4). I wonder if it would make sense to close it

@turro I didn't notice that it was the old repo, sorry about that.
